# Generated by Django 5.0 on 2024-10-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Полное описание')),
                ('content_little', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('meta_description', models.CharField(max_length=200, verbose_name='Описание для Seo')),
            ],
        ),
    ]
