# Generated by Django 5.0 on 2024-08-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Секции',
                'verbose_name_plural': 'Секция',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='other_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст_2'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст_3'),
        ),
        migrations.AddField(
            model_name='content',
            name='text_icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.section', verbose_name='Сецкия'),
        ),
    ]
