# Generated by Django 5.0 on 2024-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='content_little',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description',
            field=models.CharField(max_length=200, verbose_name='Описание для Seo'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_keywords',
            field=models.CharField(max_length=200, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
