# Generated by Django 5.0 on 2024-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID пользователя')),
                ('chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор'), ('manager', 'Менеджер')], default='client', max_length=10, verbose_name='Роль')),
            ],
        ),
    ]
