# Generated by Django 5.0 on 2024-11-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовки')),
                ('page_pars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег страницы')),
                ('name_pars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег названия товара')),
                ('price_pars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег цены')),
                ('unit_pars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег единицы измерения')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Парсер товаров',
                'verbose_name_plural': 'Парсеры',
            },
        ),
    ]
