# Generated by Django 5.0 on 2024-11-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_store', '0002_remove_parserstore_name_pars'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(blank=True, null=True, verbose_name='Цена на сайте')),
                ('new_price', models.FloatField(blank=True, null=True, verbose_name='Цена поставщика')),
                ('unit', models.CharField(default='N/A', max_length=50, verbose_name='ед. изм.')),
                ('check_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_checks', to='products.product')),
            ],
        ),
    ]
