# Generated by Django 5.0 on 2024-02-26 14:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('unp', models.CharField(blank=True, max_length=9, null=True, verbose_name='УНП')),
                ('checking_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет')),
                ('bic', models.CharField(blank=True, max_length=20, null=True, verbose_name='Бик банка')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование банка')),
                ('legal_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Юридический адрес')),
                ('contact_person', models.CharField(max_length=128, verbose_name='Контактное лицо')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес доставки')),
                ('email', models.EmailField(max_length=256, verbose_name='E-Mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарии к заказу')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.SmallIntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'В пути'), (3, 'Доставлен')], default=0, verbose_name='Статус заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('customer_type', models.CharField(choices=[('personal', 'Физическое лицо'), ('business', 'Юридическое лицо')], max_length=10, verbose_name='Тип заказчика')),
                ('delivery_method', models.CharField(choices=[('delivery', 'Доставка по адресу'), ('pickup', 'Самовывоз')], max_length=10, verbose_name='Метод доставки')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
    ]
