# Generated by Django 5.0 on 2024-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
