# Generated by Django 5.0 on 2024-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='Самовывоз', max_length=256, null=True, verbose_name='Адрес доставки'),
        ),
    ]
