# Generated by Django 5.0.2 on 2024-02-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордера'},
        ),
    ]
