# Generated by Django 5.0.2 on 2024-02-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Самовывоз', max_length=256, verbose_name='Адрес доставки'),
        ),
    ]
