# Generated by Django 5.0 on 2024-11-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Процент к товару'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, verbose_name='Процент к товару'),
        ),
    ]
