# Generated by Django 5.0 on 2024-01-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='sub_prod_categories',
            new_name='parent_prod_categories',
        ),
    ]
