# Generated by Django 5.0 on 2024-08-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (для Seo)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова (для Seo)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6, verbose_name='Процент к товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='НДС'),
        ),
    ]
