# Generated by Django 5.0 on 2024-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_markup_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Процент к товару'),
        ),
    ]
