# Generated by Django 5.0 on 2024-11-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_supplier_markup_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='markup_percentage',
        ),
    ]
