# Generated by Django 5.0 on 2024-08-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_updated_at_productcategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на продукт'),
        ),
    ]
