# Generated by Django 5.0 on 2024-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristiccategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производители', 'verbose_name_plural': 'Производитель'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='other_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='text_icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка'),
        ),
    ]
