# Generated by Django 5.0 on 2024-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_characteristiccategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=20, verbose_name='Кол-во'),
        ),
    ]
