# Generated by Django 5.0.1 on 2024-02-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_promotion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='category',
            new_name='categories',
        ),
    ]
