# Generated by Django 5.0.1 on 2024-02-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_category_promotion_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='categories',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(to='products.productcategory'),
        ),
    ]
