# Generated by Django 5.0.1 on 2024-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_promotion_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
