# Generated by Django 5.0.1 on 2024-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_supplier_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='supplier',
            field=models.ManyToManyField(to='products.supplier'),
        ),
    ]
