# Generated by Django 5.0.1 on 2024-02-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_characteristic_productcharacteristic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='parent_prod_categories',
            new_name='parent',
        ),
    ]
