# Generated by Django 5.0.1 on 2024-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_article_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, to='products.supplier'),
        ),
    ]
