# Generated by Django 5.0.1 on 2024-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_promotion_categories_alter_promotion_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='products.supplier'),
        ),
    ]
