# Generated by Django 5.0 on 2024-02-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productcategory_parent'),
        ('products', '0019_remove_product_is_active_product_quantity'),
    ]

    operations = [
    ]
