# Generated by Django 5.0 on 2024-02-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_merge_20240214_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name': 'Загрузка CSV ', 'verbose_name_plural': 'Загрузки CSV'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.ManyToManyField(through='products.ProductCharacteristic', to='products.characteristic', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Процент к товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.promotion', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
    ]
