# Generated by Django 5.0.2 on 2024-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_unit_product_image_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
